name:                voting-website
version:             0.1.0.0
github:              "jazhawang/voting-website"
license:             BSD3
author:              "Zhao Wang"
maintainer:          "jazhawang@gmail.com"
copyright:           "2020 Zhao Wang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            a website for voting experiments
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jazhawang/voting-website>

dependencies:
- base >= 4.7 && < 5
- servant-server
- servant
- aeson
- time
- warp
- wai
- mtl
- dotenv
- postgresql-simple
- resource-pool
- users
- dotenv
- envy
- text
- lens
- lens-aeson

library:
  source-dirs: src

executables:
  voting-website-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - voting-website

tests:
  voting-website-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - voting-website    
